package types

const (
	EventTypeOutgoingBatchTx       = "outgoing_batch_tx"
	EventTypeOutgoingBatchCanceled = "outgoing_batch_canceled"
	EventTypeTransferPooled        = "transfer_pooled"
	EventTypeTransferCanceled      = "transfer_canceled"
	EventTypeLogicCallCanceled     = "logic_call_canceled"
	EventTypeDelegateKey           = "delegate_key"
	EventTypeSubmitEvent           = "submit_event"
	EventTypeConfirm               = "confirm"
	EventTypeSignerSetRequest      = "signer_set_request"

	AttributeKeyOrchestratorAddr  = "orchestrator_address"
	AttributeKeyEthereumAddr      = "ethereum_address"
	AttributeKeyValidatorAddr     = "validator_address"
	AttributeKeyAttestationID     = "attestation_id"
	AttributeKeyEventID           = "event_id"
	AttributeKeyEventType         = "event_type"
	AttributeKeyConfirmID         = "confirm_id"
	AttributeKeyConfirmType       = "confirm_type"
	AttributeKeyTxID              = "tx_id"
	AttributeKeyEthRecipient      = "eth_recipient"
	AttributeKeyDenom             = "cosmos_denom"
	AttributeKeyTokenContract     = "token_contract"
	AttributeKeyRefundDenom       = "refund_denom"
	AttributeKeyNonce             = "nonce"
	AttributeKeyValsetNonce       = "valset_nonce"
	AttributeKeyInvalidationID    = "invalidation_id"
	AttributeKeyInvalidationNonce = "invalidation_nonce"
)
